# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QCloudSMHDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "QCloudCOSSMH/WithoutCoreVersion",path:"../"
  target 'QCloudSMHDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  target 'QCloudSMHDemoUITests' do
    # Pods for testing
  end
end

