# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
target 'QCloudSMHDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod "QCloudCOSSMH/Api",path:"../"
#  pod "QCloudCOSSMH/WithoutCoreVersion",git:"https://github.com/tencentyun/smh-sdk-ios.git"
  target 'QCloudSMHDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  target 'QCloudSMHDemoUITests' do
    # Pods for testing
  end
end

