module: QCloudCOSSMH
author: QCloudTerminalLab
author_url: http://qcloud.com
objc: true
clean: true
framework_root: .
umbrella_header: Pod/Classes/QCloudCOSSMH.h
sdk: iphoneos
hide_documentation_coverage: true
docset_path: com.tencent.qcloud.QCloudCOSSMH.docset
